version: '3.2'

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: std_app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: ${APP_NAME}
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    external_links:
     - db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: std_webserver
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    external_links:
     - db
     - phpmyadmin

  db:
    image: mariadb
    container_name: std_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: ${APP_NAME}
      SERVICE_TAGS: ${APP_ENV}
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
      - ./mariadb/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: std_phpmyadmin
    restart: always
    environment:
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=db
    ports:
      - 8082:80
    external_links:
      - db:db
    volumes:
      - ./phpmyadmin/sessions:/sessions
